FROM centos:8

RUN yum -y update && yum -y install curl python3 python3-pip
RUN yum -y group install "Development Tools"

RUN pip3 install --upgrade pip && pip3 install conan

ARG CMAKE_VERSION=3.13
RUN curl -SL https://cmake.org/files/v$CMAKE_VERSION/cmake-$CMAKE_VERSION.0-Linux-x86_64.tar.gz |tar -xz --strip-components=1 -C /usr/local
